apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: korpo-app
build:
  artifacts:
    - image: phpl/department-service
      context: department-service
    - image: phpl/employee-service
      context: employee-service
    - image: phpl/organization-service
      context: organization-service
    - image: phpl/gateway-service
      context: gateway-service
deploy:
  kubectl:
    manifests:
      - k8s/department-cluster-ip-service.yml
      - k8s/department-deployment.yml
      - k8s/employee-cluster-ip-service.yml
      - k8s/employee-deployment.yml
      - k8s/gateway-deployment.yml
      - k8s/gateway-cluster-ip-service.yml
      - k8s/ingress-service.yml
      - k8s/ingress-swagger-service.yml
      - k8s/metalb-config-map.yml
      - k8s/mongodb-configmap.yml
      - k8s/mongodb-secret.yml
      - k8s/organization-cluster-ip-service.yml
      - k8s/organization-deployment.yml
